// Wave-2 SEO — origin countries (~197) for "study in France from [origin]".
//
// Generated by scripts/seo/build-origins.mts from ISO 3166-1, with isEEF flagged
// from the verified Campus France «Études en France» list (source page enumerates
// 72; see that script). 196-origin doctrine: every origin is a REAL corridor —
// EEF (mandatory online procedure) or direct/consular — never a country-name swap.

import originsData from "@/data/origins.json";

export type Origin = {
  slug: string;
  name: string;
  iso2: string;
  isEEF: boolean;
  region: string;
};

export const ORIGINS = originsData as Origin[];
export const EEF_ORIGINS = ORIGINS.filter((o) => o.isEEF);
export const ORIGIN_COUNT = ORIGINS.length;

const BY_SLUG = new Map(ORIGINS.map((o) => [o.slug, o]));
export function findOrigin(slug: string): Origin | undefined {
  return BY_SLUG.get(slug);
}

// Every origin carries a real corridor (EEF or direct/consular) + real formation
// data + honest search-tuned text (search-intent line + branched FAQ), so every
// origin page is substantive and indexable — no noindex tier.
export function isIndexableOrigin(_o: Origin): boolean {
  return true;
}

export const INDEXABLE_ORIGINS = ORIGINS;

// Stable region order for grouping the origin selector.
export const REGION_ORDER = [
  "Sub-Saharan Africa", "Northern Africa", "Western Asia", "Southern Asia",
  "South-eastern Asia", "Eastern Asia", "Central Asia", "Eastern Europe",
  "Southern Europe", "Western Europe", "Northern Europe", "Northern America",
  "Latin America and the Caribbean", "Australia and New Zealand", "Melanesia",
  "Micronesia", "Polynesia", "Other",
];
